### ISSUE TITLE
BoW metric implementation

### ISSUE THREAD

**Issue by bertsky** [ulb-sachsen-anhalt/digital-eval#10]
The numerator of the metrics called `BoWs` and `BagOfWords` only counts the false negatives:

https://github.com/ulb-sachsen-anhalt/digital-eval/blob/edc8b979b3f39551d1d6c624c5ebc04076b49a74/src/digital_eval/metrics.py#L442-L451

This is then combined with a denominator that counts the length of the reference:

https://github.com/ulb-sachsen-anhalt/digital-eval/blob/971918fbb541d12446bb7a72bb8a74f91043285f/src/digital_eval/metrics.py#L167-L195

Together, this yields a pure **recall** rate calculation. 

But for recall there is already an equivalent calculation via NLTK's metrics. So I guess this should really be a calculation for **BoW accuracy**, and therefore can be considered a bug. To get the correct numerator for accuracy/error, just add the inverse diff, i.e. the counts of the false positives.

Also, the function names `accuracy_for` and `error_for` are misleading: Not only are these unnormaled rates, artificially clipped to the [0,1] interval. But more importantly, they should use the **sum** of both lengths (reference and candidate) as denominator.

**Comment by bertsky** [comment]
> Further, the calculation for this metric will be completely redone to fit what's been written in the current [OCR-D evaluation specification](https://github.com/OCR-D/spec/blob/master/ocrd_eval.md) using a multiset rather than the current Counter-set under the hood.

I do think your `Counter` set method is correct. It perfectly reflects the OCR-D eval spec (which itself based on the `count-based success` measure by PRImA, as opposed to `index-based`, which you often see in information retrieval contexts).

**Comment by M3ssman** [comment]
@bertsky 
Where do the formulas in the OCR-D eval spec originate from? 
Is a reference implementation for the BoW Error public available?
